chzzk:
  oauth:
    login-enabled: ${CHZZK_OAUTH_LOGIN_ENABLED:true}
  chat:
    auto-connect-enabled: ${CHZZK_CHAT_AUTO_CONNECT_ENABLED:true}
  client-id: ${CHZZK_CLIENT_ID}
  client-secret: ${CHZZK_CLIENT_SECRET}
  redirect-uri: ${CHZZK_REDIRECT_URI:http://localhost:8080/token}

spring:
  datasource:
    url: ${DB_URL:jdbc:h2:file:./build/local-h2/nyangnyangbot;MODE=MySQL;DATABASE_TO_LOWER=TRUE;NON_KEYWORDS=MONTH;AUTO_SERVER=TRUE}
    driver-class-name: org.h2.Driver
    username: ${DB_USER:sa}
    password: ${DB_PASS:}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

logging:
  level:
    org.hibernate.SQL: debug
