spring:
  application:
    name: nyang-nyang-bot

otel:
  instrumentation:
    logback-appender:
      experimental:
        capture-key-value-pair-attributes: true

---

spring:
  config:
    activate:
      on-profile: "!local"
    import: ${SPRING_CONFIG_IMPORT:configserver:https://spring.nowstart.org/config}
