server:
  port: 8080
  base-url: ${SERVER_BASE_URL:http://localhost:8080}
  forward-headers-strategy: native

spring:
  application:
    name: nyang-nyang-bot

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          batch_size: 50
          format_sql: true
          highlight_sql: true
          dialect: org.hibernate.dialect.MariaDBDialect

  datasource:
    url: ${DB_URL:ENC(aaC2l5twFy36wicAJjFw6dNdgEJUGs6HNHcK9z1YRGV8rRnyjchggGCHwOYJAAWrk/F6SvrUzWvx/DCcp8gJKgooROKrI2fCXWEWNu5x1GM=)}
    username: ${DB_USERNAME:ENC(8rEbRK5wP4t3G/5uvMuxpYFpjNvQdCszFCB5O47VpKpgMkkZNUMMb98acnZIlPye)}
    password: ${DB_PASSWORD:ENC(E5g3c0TOyhN1ziHJZA1czIyNuz6bVnQZsxQhoAdLOIkbXcoYaucWIxr4YIiG+iUfnw6ctMC7nkw+e+RRk8mr2A==)}

  security:
    user:
      name: ENC(1DWMT+U4oSOaV8qgepq6ZVrhcrBr2GT9+UNNM4+8PVgTsEIZOlIm7VvcMye7f1IS)
      password: ENC(jEeUwqRD0EULy1qETRiWRYBk+JeMJcJUb2GBd+VP3goCsIXfsAf7UWlvfmSk+cON)

  boot:
    admin:
      client:
        url: ${server.base-url}
        instance:
          prefer-ip: true
          metadata:
            user:
              name: ${spring.security.user.name}
              password: ${spring.security.user.password}
        username: ${spring.security.user.name}
        password: ${spring.security.user.password}
      ui:
        public-url: ${server.base-url}
        available-languages: ko
        view-settings:
          - name: wallboard
            enabled: false
          - name: journal
            enabled: false
        external-views:
          - label: "\uD638\uAC10\uB3C4"
            url: ${server.base-url}/favorite/list
            order: -9999
            iframe: true
          - label: "\uC5D1\uC140"
            url: https://docs.google.com/spreadsheets/d/1PKgmtFVrJWw4briZGxlfyKKUd3XaQscsmAGR6LZ12Os/edit?gid=1565504110#gid=1565504110
            order: -9998
            iframe: true

jasypt:
  encryptor:
    password: ${JASYPT_KEY}

google:
  spreadsheet:
    id: ENC(4hsMJwPVMud5uMCYlsY6AEofkUityI6pU68yrSgEnJHVsdG4bdFOcD6eWe08xkYIruy4deRX1xlIM+A5+lp47fVXaZqTZ8s5EwKzg63zpjU=)
    key: ./key/google_spread_sheet_key.json

chzzk:
  channelId: ${CHZZK_CHANNEL:ENC(quG85YdX+oDu/vCBG0Aubp2vv0oNBCj2DGztfUIq58T/o9a4Bdd/YrCnDyE/GkhKZQw6ZaNqam0od0GQ+o2XcnetxVoX7PVqr+ogJ87sr4g=)}
  id: ${CHZZK_AUT:ENC(jtwO/GsRfsXhSh73gLWVWOpKtw1DRp3+M0PDay4aPh3Fl+fpepCY9429OK+mFDwn)}
  password: ${CHZZK_SES:ENC(IZA+7Meykv3ZwOvi4RYDyNBiNL+Gj8j/m+kL1CSHPztufkasUCq69eoelfTssDwp)}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    os:
      enabled: true
    java:
      enabled: true
    process:
      enabled: true

logging:
  file:
    path: ./logs
  charset:
    file: UTF-8
