spring:
  application:
    name: nyang-nyang-bot
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: ${DB_URL:ENC(aaC2l5twFy36wicAJjFw6dNdgEJUGs6HNHcK9z1YRGV8rRnyjchggGCHwOYJAAWrk/F6SvrUzWvx/DCcp8gJKgooROKrI2fCXWEWNu5x1GM=)}
    username: ${DB_USERNAME:ENC(8rEbRK5wP4t3G/5uvMuxpYFpjNvQdCszFCB5O47VpKpgMkkZNUMMb98acnZIlPye)}
    password: ${DB_PASSWORD:ENC(E5g3c0TOyhN1ziHJZA1czIyNuz6bVnQZsxQhoAdLOIkbXcoYaucWIxr4YIiG+iUfnw6ctMC7nkw+e+RRk8mr2A==)}

jasypt:
  encryptor:
    password: ${JASYPT_KEY}

google:
  spreadsheet:
    id: ENC(4hsMJwPVMud5uMCYlsY6AEofkUityI6pU68yrSgEnJHVsdG4bdFOcD6eWe08xkYIruy4deRX1xlIM+A5+lp47fVXaZqTZ8s5EwKzg63zpjU=)
    key: ./key/google_spread_sheet_key.json

chzzk:
  channelId: ${CHZZK_CHANNEL_ID:ENC(quG85YdX+oDu/vCBG0Aubp2vv0oNBCj2DGztfUIq58T/o9a4Bdd/YrCnDyE/GkhKZQw6ZaNqam0od0GQ+o2XcnetxVoX7PVqr+ogJ87sr4g=)}
  id: ${CHZZK_ID:ENC(jtwO/GsRfsXhSh73gLWVWOpKtw1DRp3+M0PDay4aPh3Fl+fpepCY9429OK+mFDwn)}
  password: ${CHZZK_PASSWORD:ENC(IZA+7Meykv3ZwOvi4RYDyNBiNL+Gj8j/m+kL1CSHPztufkasUCq69eoelfTssDwp)}
  clientId:  ${CHZZK_CLIENT_ID:ENC(aWyut53qLnkrwiZum0V/8KyJ4xlpAKtq8YaR6h0ERlLbK2YDF0O9ZihGdUGOABUq6fxzUH43uHbIEDyfL/tixPqXOdu+TUX5KlTKoIzUS9s=)}
  clientPassword:  ${CHZZK_CLIENT_PASSWORD:ENC(wG+b5r5ms4bJVAyV0Gn2VxayRdxejJ2KdhttHEhYRrtBcBs2r8qwtdMYBZf8mHsmojCEnOBCStWdwVeov1nOh2Q5MObo8fg0H6hD43kmQqo=)}