server:
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: nyang-nyang-bot

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:

      hibernate:
        format_sql: true


  datasource:
    url: ${DB_URL:ENC(aaC2l5twFy36wicAJjFw6dNdgEJUGs6HNHcK9z1YRGV8rRnyjchggGCHwOYJAAWrk/F6SvrUzWvx/DCcp8gJKgooROKrI2fCXWEWNu5x1GM=)}
    username: ${DB_USERNAME:ENC(8rEbRK5wP4t3G/5uvMuxpYFpjNvQdCszFCB5O47VpKpgMkkZNUMMb98acnZIlPye)}
    password: ${DB_PASSWORD:ENC(E5g3c0TOyhN1ziHJZA1czIyNuz6bVnQZsxQhoAdLOIkbXcoYaucWIxr4YIiG+iUfnw6ctMC7nkw+e+RRk8mr2A==)}

eureka:
  instance:
    metadata-map:
      management.port: ${management.server.port}
  client:
    service-url:
        defaultZone: ${SERVICE_URL}

jasypt:
  encryptor:
    password: ${JASYPT_KEY}

google:
  spreadsheet:
    id: ENC(4hsMJwPVMud5uMCYlsY6AEofkUityI6pU68yrSgEnJHVsdG4bdFOcD6eWe08xkYIruy4deRX1xlIM+A5+lp47fVXaZqTZ8s5EwKzg63zpjU=)
    key: ./key/google_spread_sheet_key.json

chzzk:
  channelId: ${CHZZK_CHANNEL:ENC(quG85YdX+oDu/vCBG0Aubp2vv0oNBCj2DGztfUIq58T/o9a4Bdd/YrCnDyE/GkhKZQw6ZaNqam0od0GQ+o2XcnetxVoX7PVqr+ogJ87sr4g=)}
  id: ${CHZZK_AUT:ENC(jtwO/GsRfsXhSh73gLWVWOpKtw1DRp3+M0PDay4aPh3Fl+fpepCY9429OK+mFDwn)}
  password: ${CHZZK_SES:ENC(IZA+7Meykv3ZwOvi4RYDyNBiNL+Gj8j/m+kL1CSHPztufkasUCq69eoelfTssDwp)}

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    os:
      enabled: true
    java:
      enabled: true
    process:
      enabled: true

logging:
  file:
    path: ./logs
  charset:
    file: UTF-8
