{
 "title": "chzzk",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "TPM",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service_name=\"nyang-nyang-bot\"} |= \"[ChzzkChat]\" [1m]))"
    }
   ]
  },
  {
   "title": "총 메시지 양 (User Top20)",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 4, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(20, sum by (user) (count_over_time({service_name=\"nyang-nyang-bot\"} |= \"[ChzzkChat]\" | regexp \"nickname=(?P<user>[^,]+)\" [$__range])))"
    }
   ]
  },
  {
   "title": "로그",
   "type": "table",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"nyang-nyang-bot\"} |= \"[ChzzkChat]\" | regexp \"nickname=(?P<user>[^,]+)\" | regexp \"content=(?P<msg>[^,]+)\" | line_format \"{{.user}}: {{.msg}}\""
    }
   ]
  },
  {
   "title": "API 호출 (명령어 Top10)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10,\r\n  sum by (cmd) (\r\n    count_over_time(\r\n      {service_name=\"nyang-nyang-bot\"}\r\n      |= \"[ChzzkChat]\"\r\n      |= \"content=!\"\r\n      | regexp \"content=!(?P<cmd>[^\\\\s,]+)\"\r\n    [$__range])\r\n  )\r\n)\r\n"
    }
   ]
  },
  {
   "title": "타임차트",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service_name=\"nyang-nyang-bot\"} |= \"[ChzzkChat]\" [$__interval]))",
     "legendFormat": "현재"
    },
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service_name=\"nyang-nyang-bot\"} |= \"[ChzzkChat]\" [$__interval] offset 1d))",
     "legendFormat": "과거"
    }
   ]
  }
 ]
}